# Generated by Django 5.0.6 on 2024-05-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_report_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='severity_level',
        ),
        migrations.AddField(
            model_name='report',
            name='severity',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
